#!/bin/bash

# this script must be run *AFTER* the DDL is run otherwise it will fail
#java -jar target/jdbc-run-cli-0.0.15-SNAPSHOT-shaded.jar -JDBCDriverClassName org.h2.Driver -RunSQLFile /tmp/test-load -JDBCDriverPath ~/.m2/repository/com/h2database/h2/1.4.197/h2-1.4.197.jar -JDBCUrl target/db -MasterRunScriptPath /tmp/runScript.yaml

java -jar target/jdbc-run-cli-0.0.15-SNAPSHOT-shaded.jar -MasterRunScriptPath /tmp/runScript.yaml -JDBCUrl jdbc:p6spy:h2:/tmp/db-test -JDBCDriverClassName org.h2.Driver -JDBCDriverPath /home/w/.m2/repository/com/h2database/h2/1.4.197/h2-1.4.197.jar
